# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-MobileAgent
version:      0.25
version_from: lib/HTTP/MobileAgent.pm
installdirs:  site
requires:
    HTTP::Headers:                 1.43
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
